version: '3.8'

volumes:
  docker-nest-postgres:
  redis:

services:
  postgres:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST: ${DB_HOST}
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data

    env_file:
      - .env
    ports:
      - 5432:5432

  redis:
    env_file:
      - .env
    image: hub.a-azar.com/bitnami/redis:7.0.15
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
    volumes:
      - redis:/var/lib/redis

    ports:
      - 6379:6379